# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui',
# licensing of 'main.ui' applies.
#
# Created: Mon Dec  9 20:05:58 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(979, 772)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_label.sizePolicy().hasHeightForWidth())
        self.image_label.setSizePolicy(sizePolicy)
        self.image_label.setMinimumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.image_label.setFont(font)
        self.image_label.setStyleSheet("background-color: rgb(167, 173, 186);")
        self.image_label.setObjectName("image_label")
        self.verticalLayout_4.addWidget(self.image_label)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.valueMinLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.valueMinLabel.setFont(font)
        self.valueMinLabel.setObjectName("valueMinLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.valueMinLabel)
        self.valueMaxLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.valueMaxLabel.setFont(font)
        self.valueMaxLabel.setObjectName("valueMaxLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.valueMaxLabel)
        self.value_max_slider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_max_slider.sizePolicy().hasHeightForWidth())
        self.value_max_slider.setSizePolicy(sizePolicy)
        self.value_max_slider.setMaximum(255)
        self.value_max_slider.setProperty("value", 255)
        self.value_max_slider.setOrientation(QtCore.Qt.Horizontal)
        self.value_max_slider.setObjectName("value_max_slider")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.value_max_slider)
        self.areaLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.areaLabel.setFont(font)
        self.areaLabel.setObjectName("areaLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.areaLabel)
        self.area_slider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.area_slider.sizePolicy().hasHeightForWidth())
        self.area_slider.setSizePolicy(sizePolicy)
        self.area_slider.setMinimum(10000)
        self.area_slider.setMaximum(5000000)
        self.area_slider.setProperty("value", 250000)
        self.area_slider.setOrientation(QtCore.Qt.Horizontal)
        self.area_slider.setObjectName("area_slider")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.area_slider)
        self.exposureLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exposureLabel.setFont(font)
        self.exposureLabel.setObjectName("exposureLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.exposureLabel)
        self.gainLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gainLabel.setFont(font)
        self.gainLabel.setObjectName("gainLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.gainLabel)
        self.gain_slider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gain_slider.sizePolicy().hasHeightForWidth())
        self.gain_slider.setSizePolicy(sizePolicy)
        self.gain_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gain_slider.setObjectName("gain_slider")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.gain_slider)
        self.value_min_slider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_min_slider.sizePolicy().hasHeightForWidth())
        self.value_min_slider.setSizePolicy(sizePolicy)
        self.value_min_slider.setMaximum(255)
        self.value_min_slider.setOrientation(QtCore.Qt.Horizontal)
        self.value_min_slider.setObjectName("value_min_slider")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.value_min_slider)
        self.exposure_slider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exposure_slider.sizePolicy().hasHeightForWidth())
        self.exposure_slider.setSizePolicy(sizePolicy)
        self.exposure_slider.setOrientation(QtCore.Qt.Horizontal)
        self.exposure_slider.setObjectName("exposure_slider")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.exposure_slider)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.info_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_label.sizePolicy().hasHeightForWidth())
        self.info_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.info_label.setFont(font)
        self.info_label.setObjectName("info_label")
        self.verticalLayout_5.addWidget(self.info_label)
        self.radius_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radius_label.setFont(font)
        self.radius_label.setObjectName("radius_label")
        self.verticalLayout_5.addWidget(self.radius_label)
        self.printScreenOverlayButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.printScreenOverlayButton.setFont(font)
        self.printScreenOverlayButton.setObjectName("printScreenOverlayButton")
        self.verticalLayout_5.addWidget(self.printScreenOverlayButton)
        self.printScreenButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.printScreenButton.setFont(font)
        self.printScreenButton.setObjectName("printScreenButton")
        self.verticalLayout_5.addWidget(self.printScreenButton)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.half_radio_button = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.half_radio_button.setFont(font)
        self.half_radio_button.setObjectName("half_radio_button")
        self.verticalLayout_6.addWidget(self.half_radio_button)
        self.exponent_radio_button = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exponent_radio_button.setFont(font)
        self.exponent_radio_button.setObjectName("exponent_radio_button")
        self.verticalLayout_6.addWidget(self.exponent_radio_button)
        self.ninty_percent_radio_button = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ninty_percent_radio_button.setFont(font)
        self.ninty_percent_radio_button.setObjectName("ninty_percent_radio_button")
        self.verticalLayout_6.addWidget(self.ninty_percent_radio_button)
        self.off_button = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.off_button.setFont(font)
        self.off_button.setChecked(True)
        self.off_button.setObjectName("off_button")
        self.verticalLayout_6.addWidget(self.off_button)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 979, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionSave_with_overlay = QtWidgets.QAction(MainWindow)
        self.actionSave_with_overlay.setObjectName("actionSave_with_overlay")
        self.actionSave_without_overlay = QtWidgets.QAction(MainWindow)
        self.actionSave_without_overlay.setObjectName("actionSave_without_overlay")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionSave_with_overlay)
        self.menuFile.addAction(self.actionSave_without_overlay)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.image_label.setText(QtWidgets.QApplication.translate("MainWindow", "No device available", None, -1))
        self.valueMinLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Value min", None, -1))
        self.valueMaxLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Value max", None, -1))
        self.areaLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Area", None, -1))
        self.exposureLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Exposure", None, -1))
        self.gainLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Gain", None, -1))
        self.info_label.setText(QtWidgets.QApplication.translate("MainWindow", "Info", None, -1))
        self.radius_label.setText(QtWidgets.QApplication.translate("MainWindow", "Radius", None, -1))
        self.printScreenOverlayButton.setText(QtWidgets.QApplication.translate("MainWindow", "PrtScrnOver", None, -1))
        self.printScreenButton.setText(QtWidgets.QApplication.translate("MainWindow", "PrtScrn", None, -1))
        self.half_radio_button.setText(QtWidgets.QApplication.translate("MainWindow", "1/2", None, -1))
        self.exponent_radio_button.setText(QtWidgets.QApplication.translate("MainWindow", "Exp", None, -1))
        self.ninty_percent_radio_button.setText(QtWidgets.QApplication.translate("MainWindow", "90%", None, -1))
        self.off_button.setText(QtWidgets.QApplication.translate("MainWindow", "Off", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.actionSave_with_overlay.setText(QtWidgets.QApplication.translate("MainWindow", "Save with overlay as", None, -1))
        self.actionSave_without_overlay.setText(QtWidgets.QApplication.translate("MainWindow", "Save without overlay as", None, -1))
        self.actionQuit.setText(QtWidgets.QApplication.translate("MainWindow", "Quit", None, -1))

